### ISSUE TITLE
HB Rechtstexte Modul Konflikt

### ISSUE THREAD

**Issue by enderecoFlorian** [Endereco/endereco-shopware5-client#10]
Durch das HB Rechtstexte Modul kann an manchen Stellen der endereco-API-Key nicht mehr gelesen werden und somit können manche Requests nicht aufgerufen werden. Das betrifft die doAccounting und doConversion Requests. Damit ist es unmöglich abrechenbare Sessions dem Kunden in Rechnung zu stellen.

Es reicht das HB Rechtstexte Modul zu installieren um das Problem zu verursachen. Erst nach der deinstallation und cache löschen funktionieren die Requests wieder.

Eine Mögliche Lösung ist, unser api key in endereco api key umzubenennen jedoch müssen hier alle Kunden informiert werden.

**Comment by iljamobilemojo** [comment]
gelöst in 3.5.3
